# Minikube development overrides
web:
  image:
    pullPolicy: Never

api:
  image:
    pullPolicy: Never

config:
  apiUrl: "http://voyager-api:4000"
  databaseUrl: "postgresql://voyager:voyager_dev@host.minikube.internal:5432/voyager_dev"
  redisUrl: "redis://host.minikube.internal:6379"
