# Minikube development overrides
web:
  image:
    pullPolicy: Never

api:
  image:
    pullPolicy: Never

config:
  apiUrl: "http://voyager-api:4000"
  databaseUrl: "postgresql://voyager:voyager_dev@192.168.49.1:5432/voyager_dev"
  redisUrl: "redis://192.168.49.1:6379"
