namespace: voyager

web:
  replicaCount: 1
  image:
    repository: voyager-web
    tag: dev
    pullPolicy: IfNotPresent
  port: 3000

api:
  replicaCount: 1
  image:
    repository: voyager-api
    tag: dev
    pullPolicy: IfNotPresent
  port: 4000

ingress:
  enabled: true
  className: nginx
  host: voyager-platform.voyagerlabs.co

config:
  apiUrl: "http://voyager-api:4000"
  redisUrl: "redis://redis:6379"
  databaseUrl: "postgresql://voyager:voyager_dev@postgres:5432/voyager"

db:
  image:
    repository: postgres
    tag: "17-alpine"
  port: 5432
  persistence:
    enabled: true
    size: 5Gi
    storageClass: ""

redis:
  image:
    repository: redis
    tag: "7-alpine"
  port: 6379
  persistence:
    enabled: true
    size: 1Gi
    storageClass: ""

rbac:
  create: true

secret:
  dbPassword: ""  # Override per environment
  jwtSecret: ""   # Override per environment
  adminPassword: ""  # Override per environment
