apiVersion: v1
kind: ConfigMap
metadata:
  name: voyager-config
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "voyager.labels" . | nindent 4 }}
data:
  API_URL: {{ .Values.config.apiUrl | quote }}
  REDIS_URL: {{ .Values.config.redisUrl | quote }}
