apiVersion: v1
kind: ConfigMap
metadata:
  name: voyager-db-init
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "voyager.labels" . | nindent 4 }}
data:
  init.sql: |
{{ .Files.Get "sql/init.sql" | indent 4 }}
