{{- if .Values.db.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: voyager-db-data
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "voyager.labels" . | nindent 4 }}
    app.kubernetes.io/component: db
spec:
  accessModes:
    - ReadWriteOnce
  {{- if .Values.db.persistence.storageClass }}
  storageClassName: {{ .Values.db.persistence.storageClass | quote }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.db.persistence.size }}
{{- end }}
