apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "voyager.labels" . | nindent 4 }}
    app.kubernetes.io/component: db
spec:
  selector:
    app: postgres
  ports:
    - port: {{ .Values.db.port }}
      targetPort: {{ .Values.db.port }}
