apiVersion: v1
kind: Service
metadata:
  name: voyager-api
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "voyager.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.api.port }}
      targetPort: {{ .Values.api.port }}
      protocol: TCP
  selector:
    {{- include "voyager.selectorLabels.api" . | nindent 4 }}
